# Default values for bmrg-apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General Configuration
# - To enable or disable features, use the feature toggle flags under enable.
general:
  namePrefix: bmrg-flow
  enable:
    apidocs: false
    debug: false
    eventing: true
    feature:
      activity: true
      insights: true
      workflowQuotas: true
      workflowTriggers: true
      workflowTokens: true
      teamParameters: true
      globalParameters: true
      teamManagement: true
      userManagement: true
      taskManager: true
      settings: true
  externalUrl: 
    teams: 
    users: 
    navigation: 
    headerNavigation:

workers:
  security:
    enable: true
    policy: ibm-privileged-psp
  logging: 
    type: default
    host: 
    port: 
    secret: 
  enable:
    dedicatedNodes: false
  
core:
  namePrefix: bmrg-core
  ingressRoot: ""

# General Image Configuration
image:
  registry: boomerangio
  pullPolicy: IfNotPresent
  pullSecret: 

# Job Configuraiton
job:
  data:
    enabled: true
    profile: flow
    image:
      repository: /flow-loader
      tag: 0.4.25

# App Configuration
apps:
  flow:
    image:
      repository: /flow-client-web
      tag: 3.0.72
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted

# Micro Service Configuration
# Note: There are if conditions in the template referencing the service name i.e. urbancode
services:
  controller:
    image:
      repository: /flow-service-controller
      tag: 5.9.4
    replicaCount: 1
    service:
      type: ClusterIP
    serviceAccount: null
    zone: semi-trusted
  listener:
    image:
      repository: /flow-service-listener
      tag: 1.5.8
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  workflow:
    image:
      repository: /flow-service-workflow
      tag: 2.5.55
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted

# Global configuration. This can be overriden by a parent chart.
global:
  database:
    mongodb:
      host: bmrg-mdb001-ibm-mongodb-dev
      port: 27017
      user: boomerang
      password: passw0rd
      secretName: 
  ingress:
    enabled: false
    root: /flow
    host: cloud.boomerangplatform.net
    tlsSecretName: bmrg-tls-cloud
    # The prefix for the annotations inside the ingress definition. Typically for IKS Community Ingress
    # you need to set it to "nginx.ingress.kubernetes.io"
    annotationsPrefix: "ingress.kubernetes.io"
    # The class of the ingress, it is used to mark the ingress resources to be picked-up by a specific 
    # controller. For IKS Community Ingress set it to "public-iks-k8s-nginx"
    class: "nginx"
  auth:
    enabled: false
    mode: basic
    serviceName: bmrg-auth-proxy
    namespace: bmrg-core
    prefix: /oauth
    tokenURL: http://bmrg-core-services-auth.bmrg-core.svc.cluster.local/auth/token/validate/external
    signOutRedirect: 

hostAliases: []

proxy:
  enable: false
  host:
  port:

monitoring:
  newrelic:
    apm:
      name: Boomerang Private
      key:
      image: 
        registry: boomerangio
        repository: /util-newrelicjavaagent
        tag: 5.14.0
    browser:
      id:
      key:
  jaeger: 
    enabled: false
    namespace: 
    agent: 
      host: jaeger-dev-agent
      port: 6831
    collector: 
      host: jaeger-dev-collector
      port: 14268
    remoteControlledSampler: 
      host: jaeger-dev-agent
      port: 5778

nats:
  enable: true
  url: nats://bmrg-nats:4222
  cluster: bmrg-stan

tekton: 
  enabled: false