apiVersion: v2
name: bmrg-bosun
description: Boomerang Bosun
type: application
version: 2.2.1
appVersion: "1.0.2"
home: https://useboomerang.io
dependencies:
  - name: bmrg-common
    repository: https://raw.githubusercontent.com/boomerang-io/charts/index
    version: ~3.0.1
    alias: ch
keywords:
- boomerang
- bosun
